/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package dio.lang

import org.junit.jupiter.params.ParameterizedTest
import org.junit.jupiter.params.provider.Arguments
import org.junit.jupiter.params.provider.MethodSource
import java.util.stream.Stream
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNotNull

class LexerTest {

    companion object {
        @JvmStatic
        fun happyTests(): Stream<Arguments> {
            return Stream.of(
                Arguments.of("let test = 1", listOf(
                    Token(TokenType.Assignment, 0, 0, 3, "let"),
                    Token(TokenType.Identifier, 0, 4, 8, "test"),
                    Token(TokenType.Equals, 0, 9, 10, "="),
                    Token(TokenType.Number, 0, 11, 12, "1"),
                ))
            )
        }
    }

    @ParameterizedTest
    @MethodSource("happyTests")
    fun appHasAGreeting(string: String, result: List<Token>) {
        val classUnderTest = Lexer(string)
        assertEquals(result, classUnderTest.lex().expressions)
    }
}
